### PR TITLE
New transition animation + Extra portraits support

### PR DESCRIPTION
**Pull request by Goganidze**
Attempt 2

### CODE REVIEW

**Comment by Meowlala** [comment]
This is looking much cleaner already! Thanks for working on this.

**Comment by Goganidze** [comment]
Is there anything that needs to be changed/added?

**Comment by guwahavel** [comment]
> Is there anything that needs to be changed/added?

It seems good but it does not seem to use a Custom Stage's transition jingle set by the SetTransitionMusic function. This is noticeable for Revelations which adds a custom transition jingle. Didn't notice anything weird otherwise.

**Comment by Goganidze** [comment]
> 
> It seems good but it does not seem to use a Custom Stage's transition jingle set by the SetTransitionMusic function. This is noticeable for Revelations which adds a custom transition jingle. Didn't notice anything weird otherwise.

Weird, I have the custom jingle playing. Maybe you have Excelsior installed?

**Comment by guwahavel** [comment]
Ah my bad, didn't realize Excelsior was set to override the Rev transition jingle. Everything seems good then.

**Pull request merged**
